# Generated by Django 4.2.11 on 2024-03-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("num_bedrooms", models.IntegerField()),
                ("num_bathrooms", models.IntegerField()),
                ("square_footage", models.IntegerField()),
                ("address", models.CharField(max_length=200)),
            ],
        ),
    ]
